apiVersion: 1

groups:
  - orgId: 1
    name: log-alerts
    folder: Logs
    interval: 1m
    rules:
      - uid: loki_error_rate
        title: Loki ERROR rate > 0 (5m)
        condition: A
        data:
          - refId: A
            datasourceUid: loki
            queryType: range
            relativeTimeRange:
              from: 300
              to: 0
            model:
              editorMode: code
              expr: sum by (service) (count_over_time({level="ERROR"}[5m])) > 0
        noDataState: NoData
        execErrState: Error
        for: 2m

