# AWS 配置示例
aws:
  region: us-east-1  # AWS 区域
  access-key-id: ${AWS_ACCESS_KEY_ID:your-access-key}  # AWS 访问密钥ID
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}  # AWS 访问密钥
  s3:
    bucket: ${AWS_S3_BUCKET:your-bucket-name}  # S3 存储桶名称
    region: ${AWS_S3_REGION:us-east-1}  # S3 区域（可以与主区域不同）
    endpoint: ${AWS_S3_ENDPOINT:}  # 可选：自定义端点（用于兼容S3的服务）
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:3600}  # 预签名URL过期时间（秒）