server:
  port: 8520

spring:
  application:
    name: qiaoya-community
  profiles:
    active: ${ENVIRONMENT:PROD}

  # 数据库配置
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:qiaoya_community}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Ensure each DB connection uses Asia/Shanghai so DEFAULT CURRENT_TIMESTAMP is correct
      connection-init-sql: "SET TIME ZONE 'Asia/Shanghai'"

  jackson:
    # Ensure JSON serialization/deserialization uses Asia/Shanghai
    time-zone: Asia/Shanghai

  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # FlyWay配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
    banner: false
  mapper-locations: classpath:mapper/*.xml

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:your-access-key-secret}
    bucket-name: ${ALIYUN_OSS_BUCKET:your-bucket-name}
    region: ${ALIYUN_OSS_REGION:cn-hangzhou}
    role-arn: ${ALIYUN_STS_ROLE_ARN:acs:ram::your-account-id:role/your-role-name}
    presigned-url-expiration: 3600
    callback:
      url: ${ALIYUN_OSS_CALLBACK_URL:https://qiaoya.xhyovo.cn/api/public/oss-callback}
      body: filename=${object}&size=${size}&mimeType=${mimeType}&height=${imageInfo.height}&width=${imageInfo.width}
      body-type: application/x-www-form-urlencoded
  # 邮件服务配置
  email:
    smtp:
      host: ${ALIYUN_EMAIL_SMTP_HOST:smtpdm.aliyun.com}
      port: ${ALIYUN_EMAIL_SMTP_PORT:25}
      username: ${ALIYUN_EMAIL_USERNAME:your-email@your-domain.com}
      password: ${ALIYUN_EMAIL_PASSWORD:your-smtp-password}
      sender-name: ${ALIYUN_EMAIL_SENDER_NAME:敲鸭社区}
      enabled: ${ALIYUN_EMAIL_ENABLED:true}

# 日志配置
logging:
  level:
    org.xhy.community: debug
    org.springframework.web: info
    com.baomidou.mybatisplus: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# 邮件品牌配置
community:
  email:
    brand:
      # 支持 URL 或 data URI；若留空，将尝试从 logoFile/classpath 默认位置读取
      # logoSrc: ""
      # 使用 classpath 中的 logo 文件自动生成 data URI
      logoFile: classpath:branding/logo-email.jpg
      # 页脚“管理通知设置”链接
      manageNotificationsUrl: /dashboard/user-backend/profile
  # 站点基础域名（用于将相对路径解析为绝对 URL）
  web:
    base-url: ${COMMUNITY_WEB_BASE_URL:http://code.dev.xhyovo.cn/}
