version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
    # 让 Prometheus 能访问宿主机端口（抓取 /actuator/prometheus）
    extra_hosts:
      - "host.docker.internal:host-gateway"
  loki:
    image: grafana/loki:2.9.2
    command: ["-config.file=/etc/loki/loki-config.yml"]
    ports:
      - "3100:3100"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    deploy:
      resources:
        limits:
          memory: 512M

  promtail:
    image: grafana/promtail:2.9.2
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/xhy/IdeaProjects/qiaoya-community/qiaoya-community-backend/logs:/var/log/app:ro
      - promtail-positions:/tmp
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 64M

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "5601:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=change_me
      - LOKI_URL=http://loki:3100
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
      - prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  loki-data:
  promtail-positions:
  grafana-data:
  prometheus-data:
