name: CI/CD Dev

on:
  push:
    branches: [ dev ]

concurrency:
  group: dev-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      # 国内仓库配置（例如：registry.cn-hangzhou.aliyuncs.com）
      CN_REGISTRY: ${{ secrets.CN_REGISTRY }}
      # 完整仓库路径（例如：registry.cn-hangzhou.aliyuncs.com/namespace/qiaoya-community）
      CN_IMAGE: ${{ secrets.CN_IMAGE }}
      IMAGE_NAME: ${{ github.repository }}
      TAG_SHA: dev-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to CN Registry
        if: ${{ env.CN_REGISTRY != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CN_REGISTRY }}
          username: ${{ secrets.CN_USERNAME }}
          password: ${{ secrets.CN_PASSWORD }}

      - name: Build and push image (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push image (CN Registry)
        if: ${{ env.CN_IMAGE != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.CN_IMAGE }}:dev-latest
            ${{ env.CN_IMAGE }}:${{ env.TAG_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy via SSH (dev)
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          SCRIPT_PATH: ${{ secrets.DEPLOY_SCRIPT_PATH }}
          IMAGE: ${{ env.CN_IMAGE != '' && format('{0}:dev-latest', env.CN_IMAGE) || format('{0}/{1}:dev-latest', env.REGISTRY, env.IMAGE_NAME) }}
          PROFILE: dev
          PORT: 8520
          CONTAINER_NAME: qiaoya-community-backend
          CN_REGISTRY: ${{ env.CN_REGISTRY }}
          CN_USERNAME: ${{ secrets.CN_USERNAME }}
          CN_PASSWORD: ${{ secrets.CN_PASSWORD }}
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          envs: GHCR_USERNAME,GHCR_TOKEN,SCRIPT_PATH,IMAGE,PROFILE,PORT,CONTAINER_NAME,CN_REGISTRY,CN_USERNAME,CN_PASSWORD
          script: |
            set -e
            SCRIPT_PATH="${SCRIPT_PATH:-/www/project/qiaoya/deploy-qiaoya.sh}"
            # 如 CN 仓库是私有，需要在服务器侧登录
            if [ -n "${CN_REGISTRY}" ] && [ -n "${CN_USERNAME}" ] && [ -n "${CN_PASSWORD}" ]; then
              echo "${CN_PASSWORD}" | docker login "${CN_REGISTRY}" -u "${CN_USERNAME}" --password-stdin
            fi
            chmod +x "$SCRIPT_PATH" || true
            "$SCRIPT_PATH"
